POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "andersonzero0",
  "password": "123"
}

### Obter todos os usuários
GET http://localhost:3000/users
Content-Type: application/json

### Obter um usuário específico
GET http://localhost:3000/users/andersonzero0
Content-Type: application/json

### Gerar token RTMP
GET http://localhost:3000/users/generate-rtmp-token/4396f847-7dba-431f-90ff-431b88f185b0?password=123
Content-Type: application/json

### Atualizar um usuário
PUT http://localhost:3000/users/dc19e037-2f53-4a79-a2f3-ee3bf35201ce
Content-Type: application/json

{
  "username": "updatedUser",
  "password": "updatedPassword"
}

### Atualizar o status de streaming de um usuário
PATCH http://localhost:3000/users/testUser/streaming/true
Content-Type: application/json

### Deletar um usuário
DELETE http://localhost:3000/users/7e140e7a-b4aa-45df-bd86-0f5c2af92ff2
Content-Type: application/json